# Base image with Node
FROM node:20-slim

# Install global Ionic CLI (optional)
RUN npm install -g @ionic/cli

# Set workdir
WORKDIR /app

# Copy everything
COPY . /app


# Go to App subdir and install
WORKDIR /app/OSCAL-CAT-App
RUN npm ci && npm run build

# Expose port
EXPOSE 4200

# Start dev server
CMD ["npm", "run", "start", "--", "--host=0.0.0.0"]
